#
# @file BUILD
# 
# @author y-ksst / created on 2021/12/09
#
# load( "@cv//:cv_deploy.bzl", "cv_deploy" )

load( "@gwrt//Main:gwrt.bzl", "gwrt_library" )

gwrt_library(
    name = "Include",
    hdrs = [
      "Hand.hpp",
      "Player.hpp",
      "Strategy.hpp",
      "ProbStrategy.hpp",
      "WinningStrategy.hpp"
    ],
    srcs = [
      "Hand.cpp",
      "Player.cpp",
      "Strategy.cpp",
      "ProbStrategy.cpp",
      "WinningStrategy.cpp"
    ],
    copts = [],
    deps = [],
)