#
# @file BUILD
# 
# @author y-ksst / created on 2021/12/09
#
# load( "@cv//:cv_deploy.bzl", "cv_deploy" )

load( "@gwrt//Main:gwrt.bzl", "gwrt_library" )

gwrt_library(
    name = "Include",
    hdrs = [
      "ListFactory.hpp",
      "ListLink.hpp",
      "ListPage.hpp",
      "ListTray.hpp",
      "Factory.hpp",
      "Link.hpp",
      "Page.hpp",
      "Tray.hpp",
      "Item.hpp"
    ],
    srcs = [
      "ListFactory.cpp",
      "ListLink.cpp",
      "ListPage.cpp",
      "ListTray.cpp",
      "Factory.cpp",
      "Link.cpp",
      "Page.cpp",
      "Tray.cpp",
      "Item.cpp"
    ],
    copts = [],
    deps = [],
)