#
# @file BUILD
# 
# @author y-ksst / created on 2021/12/09
#
# load( "@cv//:cv_deploy.bzl", "cv_deploy" )

load( "@gwrt//Main:gwrt.bzl", "gwrt_library" )

gwrt_library(
    name = "Include",
    # ここにヘッダーファイル名を挿入
    hdrs = [
      "JPNChar.hpp",
      "JPNCharFactory.hpp",
      "JPNString.hpp"
      ],
    # ここにソースファイル名を挿入
    srcs = [
      "JPNChar.cpp",
      "JPNCharFactory.cpp",
      "JPNString.cpp"
    ],
    copts = [],
    deps = [],
)